name: Java CI with Gradle and Coverage

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: Task_1_2

      - name: Run Tests and Generate JaCoCo Report
        run: ./gradlew test
        working-directory: Task_1_2

      - name: Add JaCoCo PR Comment
        uses: madrapps/jacoco-report@v1.2
        if: always()
        with:
          paths: ${{ github.workspace }}/Task_1_2/app/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 80